
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

mqtt:
  # certificate: "PATH_TO_CA.crt"
  broker: localhost
  port: 1883
  client_id: hass
  # username: "MQTT_USERNAME"
  # password: !secret MQTT_PASSWORD
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  db_url: !secret recorder_db_url
