
# based on:
# https://github.com/renemarc/home-assistant-config

version: '3'

services:

# @TODO
# add zwavejs2mqtt
# https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/quick-start?id=minimum-settings

  mqtt:
    container_name: mosquitto
    image: toke/mosquitto:latest
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mqtt/mosquitto.conf

  mariadb:
    container_name: mariadb3
    image: bianjp/mariadb-alpine:latest
    restart: unless-stopped
    ports:
      - "3306:3306/tcp"
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        
  hass:
    container_name: hass
    image: homeassistant/home-assistant:latest
    ports:
      - 8123:8123
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host  # HASS Requirement
    depends_on:
      - mqtt
      - mariadb
    
  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    restart: unless-stopped
    environment:
      APP_DAEMON_TOKEN: ${APP_DAEMON_TOKEN}
      APP_DAEMON_LONGITUDE: ${APP_DAEMON_LONGITUDE}
      APP_DAEMON_LATITUDE: ${APP_DAEMON_LATITUDE}
      APP_DAEMON_ELEVATION: ${APP_DAEMON_ELEVATION}
      APP_DAEMON_TZ: ${TZ}
      TIBBER_TOKEN: ${TIBBER_TOKEN}
    ports:
      - 5050:5050
    volumes:
      - ./appdaemon/config:/conf
    depends_on:
      - hass
      - mqtt
      
volumes:
  database-data:
