
# based on:
# https://github.com/renemarc/home-assistant-config

version: '3'

services:

# @TODO
# add zwavejs2mqtt
# https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/quick-start?id=minimum-settings

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    environment:
      NGINX_DOMAIN: ${NGINX_DOMAIN:?error}
      NGINX_PROXY_URL: ${NGINX_PROXY_URL:?error}
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/nginx/ssl:ro
    depends_on:
      - certbot

  mqtt:
    container_name: mosquitto
    image: toke/mosquitto:latest
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mqtt/mosquitto.conf

  mariadb:
    container_name: mariadb
    image: bianjp/mariadb-alpine:latest
    restart: unless-stopped
    ports:
      - "3306:3306/tcp"
    volumes:
      - database-data:/var/lib/mysql
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?error}
      MYSQL_DATABASE: ${MYSQL_DATABASE:?error}
      MYSQL_USER: ${MYSQL_USER:?error}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?error}
        
  hass:
    container_name: hass
    image: homeassistant/home-assistant:latest
    ports:
      - 8123:8123
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host  # HASS Requirement
    depends_on:
      - mqtt
      - mariadb
      - nginx
    
  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    restart: unless-stopped
    environment:
      APP_DAEMON_TOKEN: ${APP_DAEMON_TOKEN:?error}
      APP_DAEMON_LONGITUDE: ${APP_DAEMON_LONGITUDE:?error}
      APP_DAEMON_LATITUDE: ${APP_DAEMON_LATITUDE:?error}
      APP_DAEMON_ELEVATION: ${APP_DAEMON_ELEVATION:?error}
      APP_DAEMON_TZ: ${TZ:?error}
      TIBBER_TOKEN: ${TIBBER_TOKEN:?error}
    ports:
      - 5050:5050
    volumes:
      - ./appdaemon/config:/conf
    depends_on:
      - hass
      - mqtt
      
volumes:
  database-data:
