AveragePower:
  module: power
  class: AveragePowerConsumption
  sensor: sensor.power_hjemme
  ticks: 900
  wait: 60
  input_field: input_number.moving_average

# Tibber:
#   module: tibber
#   class: PriceManager
